import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import AdminHeader from "./AdminHeader";
import "@/app/globals.css";
import { Toaster } from "react-hot-toast";
import Providers from "../components/Providers";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-poppins",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function AdminLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${poppins.variable} antialiased`}>
      <body className="flex flex-col min-h-screen">
        <AdminHeader />
        <main className="flex-1 w-full max-w-[1280px] mx-auto px-4">
           <Providers>{children}</Providers>
          <Toaster position="top-right" />
        </main>
      </body>
    </html>
  );
}
